name: linting, testing, building
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    pipeline:
        runs-on: windows-latest
        strategy:
            matrix:
                node-version: [20.x]
        steps:
            - uses: actions/checkout@v2
            - name: Staring Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: install modules
              run: npm install
            - name: build production project
              run: npm run build:prod
              if: always()
            - name: linting ts
              run: npm run lint:ts
              if: always()
            - name: linting css
              run: npm run lint:scss
              if: always()
            - name: testing unit
              run: npm run test:unit
              if: always()
            - name: build storybook
              run: npm run build-storybook
              if: always()
            # - name: run regression tests
            #   run: npm run test:loki:ci
            #   if: always()
            - name: Archive screenshots
              if: ${{ failure() }}
              uses: actions/upload-artifact@v1
              with:
                  name: design-system
                  path: .loki
